---
name: "relay_tweet_to_slack_conditional"
description: "Relay Tweet to the Slack channel using a mistral workflow with a conditional"
enabled: true
pack: "twitter"

trigger:
  type: "twitter.matched_tweet"
  parameters: {}

action:
  ref: "slack.post_tweet_if_not_stackstorm_bot"
  parameters:
      twitter_handle: "{{trigger.user.screen_name}}"
      created_at: "{{trigger.created_at}}"
      tweet_text: "{{trigger.text}}"
      tweet_url: "{{trigger.url}}"
      